import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import DaliceNavbar from "./components/DaliceNavbar";

const rubik = Rubik({
  subsets: ['latin'],
  display: "swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={rubik.className}
      >
       <DaliceNavbar/>
        {children}
        <Footer/> 
      </body>
    </html>
  );
}
